<a href="https://colab.research.google.com/github/NemoStar123/AAI2026/blob/main/Exercise2_ReACT_CodeGen.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Exercise 2 — Code Generation with ReACT Prompting

Tools Used: Google Colab, GBT

## Goal
Use a ReACT-style cycle:
Reason → Act → Run → Observe → Fix → Re-run

Task:
1. Loaded a CSV of pre made student grades
2. Compute per-student average
3. Flag students with average < 80 as "At Risk"
4. Demonstrate an error and fix it


## ReACT Prompt Structure

**Reason / Plan**
- Load student_grades.csv
- Compute average across math, science, english
- Handle missing values
- Flag students below 80

**Act**
Generate Python code.

**Run**
Execute the code.

**Observe**
Capture spelling errors.

**Fix**
Correct the issue and rerun.

In [1]:

# Create student_grades.csv

import pandas as pd
import numpy as np

data = {
    "student": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "math": [85, 78, 92, 88, 76],
    "science": [90, 74, 89, 85, np.nan],
    "english": [88, 82, 94, 79, 75]
}

df = pd.DataFrame(data)
df.to_csv("student_grades.csv", index=False)
df

   student  math  science  english
0    Alice    85     90.0       88
1      Bob    78     74.0       82
2  Charlie    92     89.0       94
3    David    88     85.0       79
4      Eva    76      NaN       75


## Run Buggy Code (Intentional Error)
This demonstrates iteration evidence.

In [2]:

import pandas as pd

df_bug = pd.read_csv("student_grades.csv")

# Intentional typo: 'sciene'
df_bug["average"] = df_bug[["math", "sciene", "english"]].mean(axis=1)

df_bug["status"] = df_bug["average"].apply(lambda x: "At Risk" if x < 80 else "OK")

df_bug

KeyError: "['sciene'] not in index"


## Observation
The previous cell raises a KeyError due to a misspelled column name.
We will fix it below.

In [3]:

df_fixed = pd.read_csv("student_grades.csv")

df_fixed["average"] = df_fixed[["math", "science", "english"]].mean(axis=1, skipna=True)

df_fixed["status"] = df_fixed["average"].apply(lambda x: "At Risk" if x < 80 else "OK")

df_fixed

   student  math  science  english    average   status
0    Alice    85     90.0       88  87.666667       OK
1      Bob    78     74.0       82  78.000000  At Risk
2  Charlie    92     89.0       94  91.666667       OK
3    David    88     85.0       79  84.000000       OK
4      Eva    76      NaN       75  75.500000  At Risk


## Status Counts

In [4]:

df_fixed["status"].value_counts()

status
OK         3
At Risk    2
Name: count, dtype: int64


## Notes

Before: Column name was misspelled ('sciene'), causing KeyError.

After: Corrected to 'science' and used skipna=True to handle missing values.

 Demonstrates the full ReACT cycle and successful execution.